config/routes.rb
Rails.application.routes.draw do

  get 'searches/search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "homes#top"
  get "home/about" => "homes#about"
  get "/search" => "searches#search"
  get "book_search" => "homes#book_search"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
  end

end

app/models/group.rb
class Group < ApplicationRecord
  attachment :image
  has_many :group_users
  has_many :users, through: :group_users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
before_action :ensure_correct_user, only: [:edit, :update]
  def index
     @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to  groups_path
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
    redirect_to groups_path
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    @group.save
    redirect_to groups_path
  end


  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    if @group.owner_id != current_user.id
     redirect_to groups_path
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class = "container">
  <div class = "row">
   <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto mt-3">
     <h2>Editing Group</h2>
     <%= form_with model: @group, local: true do |f| %>
     <div class = "form-group">
      <%= f.label :グループ名 %>
      <%= f.text_field :name, class:"form-control" %>
     </div>
     <div class = "form-group">
      <%= f.label :紹介文 %>
      <%= f.text_area :introduction, class: "form-control" %>
     </div>
     <div class = "form-group">
      <%= f.label :グループ画像 %>
      <%= f.attachment_field :image, class:"form-control-file" %>
     </div>
     <%= f.submit class:"btn btn-info" %>
     <% end %>
   </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class = "container mt-3">
  <div class = "row">
   <div class = "col-md-3">
    <%= render "users/info", user: current_user %>
    <h2>New book</h2>
    <%= render "books/form", book: @book %>
   </div>
   <div class = "col-md-8 offset-md-1">
    <h2>Groups</h2>
    <table class = "table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>グループ名</th>
          <th>紹介文</th>
          <th>メンバー数</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @groups.each do |group| %>
        <tr>
          <td>
            <%= attachment_image_tag group, :image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
          </td>
          <td><%= link_to group.name, group_path(group) %></td>
          <td><%= group.introduction %></td>
          <td><%= group.users.count %></td>
          <% if group.owner_id == current_user.id %>
           <td><%= link_to "Edit",  edit_group_path(group), class:"btn btn-success btn-sm" %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
   </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class = "container">
  <div class = "row">
   <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto mt-3">
     <h2>Create Group</h2>
     <%= form_with model: @group, local: true do |f| %>
     <div class = "form-group">
      <%= f.label :グループ名 %>
      <%= f.text_field :name, class:"form-control" %>
     </div>
     <div class = "form-group">
      <%= f.label :紹介文 %>
      <%= f.text_area :introduction, class: "form-control" %>
     </div>
     <div class = "form-group">
      <%= f.label :グループ画像 %>
      <%= f.attachment_field :image, class:"form-control-file" %>
     </div>
     <%= f.submit class:"btn btn-info" %>
     <% end %>
   </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class = "container mt-3">
  <div class = "row">
    <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto mt-3">
      <h2>Event Mail</h2>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class = "container mt-3">
 <div class = "row">
   <div class = "col-md-3">
   <%= render "users/info", user: current_user %>
   <h2>New book</h2>
   <%= render "books/form", book: @book %>
   </div>
   <div class = "col-md-8 offset-md-1">
    <h2>Group Detail</h2>
    <table class = "table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>グループ名</th>
          <th>紹介文</th>
          <th>メンバー</th>
          <th colspan = "3"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <%= attachment_image_tag @group, :image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
          </td>
          <td><%= @group.name %></td>
          <td><%= @group.introduction %></td>
          <td>
              <% @group.users.each do |user| %>
                <%= user.name %>
              <% end %>
            </td>
          <% if @group.owner_id == current_user.id  %>
            <td><%= link_to "Edit", edit_group_path(@group), class:"btn btn-success btn-sm" %></td>
            <td><%= link_to 'Notice an Event', group_new_mail_path(@group), class: "btn btn-info btn-sm" %></td>
           <% elsif @group.users.include?(current_user) %>
            <td><%= link_to "Leave this group", group_path(@group), method: :delete, class:"btn btn-danger btn-sm" %></td>
          <% else %>
            <td><%= link_to "Join this group", group_join_path(@group), class:"btn btn-success" %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
   </div>
 </div>
</div>